#!/bin/sh


ln -s deb.svg application-x-deb.svg
ln -s image-x-generic.svg application-ffDiaporama.svg
ln -s image-x-eps.svg application-illustrator.svg
ln -s text-x-javascript.svg application-javascript.svg
ln -s application-x-sharedlib.svg application-octet-stream.svg 
ln -s encrypted.svg application-pgp-encrypted.svg
ln -s application-pgp-keys.svg application-pgp-signature.png
ln -s application-pgp-keys.svg application-pkcs7.mime.svg
ln -s application-pgp-keys.svg application-pkcs7.signature.svg
ln -s video-x-generic.svg application-ram.svg
ln -s text-enriched.svg application-rtf.svg
ln -s x-office-drawing.svg application-vnd.oasis.opendocument.drawing.svg 
ln -s x-office-drawing.svg application-vnd.oasis.opendocument.drawing-template.svg
ln -s x-office-drawing.svg application-vnd.oasis.opendocument.graphics.svg
ln -s x-office-drawing.svg application-vnd.oasis.opendocument.image.svg
ln -s application-vnd.sun.xml.impress.svg application-vnd.oasis.opendocument.presentation.svg
ln -s application-vnd.sun.xml.impress.template.svg application-vnd.oasis.opendocument.presentation-template.svg 
ln -s application-vnd.sun.xml.calc.template.svg application-vnd.oasis.opendocument.spreadsheet-template.svg
ln -s x-office-spreadsheet.svg application-vnd.oasis.opendocument.spreadsheet.svg 
ln -s x-office-document.svg application-vnd.oasis.opendocument.text.svg
ln -s x-office-document.svg application-vnd.oasis.opendocument.text-master.svgln 
ln -s text-x-generic-template.svg application-vnd.oasis.opendocument.text-template.svg
ln -s video-x-generic.svg application-vnd.rn-realmedia.svg
ln -s x-office-spreadsheet.svg application-vnd.stardivision.cal.svg
ln -s application-vnd.oasis.opendocument.chart.svg application-vnd.stardivision.draw.svg
ln -s x-office-spreadsheet.svg application-vnd.sun.xml.calc.svg
ln -s x-office-drawing.svg application-vnd.sun.xml.draw.svg
ln -s x-office-drawing.svg application-vnd.sun.xml.draw.template.svg
ln -s text-richtext.svg application-vnd.sun.xml.wordperfect.svg
ln -s text-richtext.svg application-vnd.sun.xml.writer.svg
ln -s text-richtext.svg application-vnd.sun.xml.writer.global.svg
ln -s text-richtext.svg application-x-abiword.svg
ln -s text-richtext.svg application-x-mswrite.svg
ln -s text-richtext.svg application-x-lyx.svg
ln -s text-richtext.svg application-x-kword.svg
ln -s text-richtext.svg application-x-applix-word.svg
ln -s application-x-7zip.svg application-x-7z-compressed.svg
ln -s application-x-archive.svg application-x-compressed.svg
ln -s application-x-tar.svg application-x-compressed-tar.svg
ln -s application-x-tar.svg application-x-xz-compressed-tar.svg
ln -s application-x-tar.svg application-x-bzip-compressed-tar.svg
ln -s application-x-tar.svg application-x-lzma-compressed-tar.svg
ln -s application-x-zip.svg zip.svg
ln -s application-x-rar.svg rar.svg
ln -s application-x-archive.svg application-x-bzdvi.svg
ln -s application-x-archive.svg application-x-compress.svg
ln -s application-x-archive.svg application-x-cpio.svg
ln -s application-x-rar.svg application-vnd.rar.svg
ln -s application-x-zip.svg application-zip.svg
ln -s application-x-executable.svg application-x-desktop.svg
ln -s font-x-generic.svg application-x-font-bdf.svg
ln -s font-x-generic.svg application-x-font-pcf.svg
ln -s font-x-generic.svg application-x-font-afm.svg
ln -s application-x-theme.svg application-x-gnome-theme-package.svg
ln -s application-vnd.sun.xml.calc.svg  application-x-gunmeric.svg
ln -s application-x-archive.svg application-x-gzdvi.svg
ln -s text-xhtml+xml.svg application-xhtml+xml.svg
ln -s application-x-cd-image.svg application-x-img.svg
ln -s application-x-cd-image.svg application-x-iso.svg
ln -s text-x-java.svg application-x-java.svg
ln -s application-x-jar.svg application-x-java-archive.svg
ln -s text-x-javascript.svg application-x-javascript.svg
ln -s audio-x-generic.svg application-x-jokosher.svg
ln -s x-office-drawing.svg application-x-kontour.svg
ln -s image-x-generic.svg application-x-krita.svg
ln -s application-x-archive.svg application-x-lzop.svg
ln -s text-x-script.svg application-x-m4.svg
ln -s video-x-generic.svg application-x-matroska.svg
ln -s text-xhtml+xml.svg application-xml.svg
ln -s application-x-sharedlib.svg application-x-object.svg
ln -s application-x-archive.svg application-x-pak.svg
ln -s application-x-qet-project.svg application-x-qet-element.svg
ln -s application-vnd.sun.xml.calc.svg application-x-quattropro.svg
ln -s application-x-cd-image.svg application-x-raw-disk-image.svg
ln -s rpm.svg application-x-rpm.svg
ln -s application-x-flash-video.svg application-x-shockwave-flash.svg
ln -s application-vnd.sun.xml.calc.svg application-x-siag.svg
ln -s text-xhtml+xml.svg application-xslt+xml.svg
ln -s text-x-sql.svg application-x-sqlite2.svg
ln -s text-x-sql.svg application-x-sqlite3.svg
ln -s application-x-subrip.svg application-x-srt.svg
ln -s application-x-subrip.svg application-x-srtrip.svg
ln -s application-x-tar.svg application-x-tarz.svg
ln -s x-office-drawing.svg application-x-tgif.svg
ln -s application-x-tar.svg application-x-tzo.svg
ln -s x-office-drawing.svg application-x-wmf.svg
ln -s application-x-tar.svg application-x-zoo.svg
ln -s empty.svg application-x-zerosize.svg
ln -s audio-x-generic.svg audio-aac.svg
ln -s audio-x-generic.svg audio-ac3.svg
ln -s audio-x-generic.svg audio-mp2.svg
ln -s audio-x-mpeg.svg audio-mp3.svg
ln -s audio-x-generic.svg audio-mp4.svg
ln -s audio-x-mpeg.svg audio-mpeg.svg
ln -s audio-x-generic.svg audio-x-adpcm.svg
ln -s audio-x-generic.svg audio-x-aiff.svg
ln -s audio-x-generic.svg audio-x-flac.svg
ln -s audio-x-generic.svg audio-x-it.svg
ln -s audio-x-generic.svg audio-x-monkey.svg 
ln -s audio-x-generic.svg audio-x-mp2.svg
ln -s audio-x-generic.svg audio-x-xi.svg 
ln -s audio-x-generic.svg audio-x-xm.svg
ln -s audio-x-vorbis+ogg.svg audio-x-flac+ogg.svg
ln -s audio-x-vorbis+ogg.svg audio-x-speex+ogg.svg
ln -s audio-x-generic.svg music.svg
ln -s audio-x-generic.svg sound.svg
ln -s audio-x-generic.svg text-vnd.abc.svg
ln -s video-x-generic.svg divx.svg
ln -s image-gif.svg gif.svg
ln -s x-office-drawing.svg gnome-mime-application-vnd.oasis.opendocument.graphics.svg
ln -s x-office-drawing.svg gnome-mime-application-vnd.oasis.opendocument.image.svg
ln -s x-office-drawing.svg gnome-mime-application-vnd.sun.xml.draw.svg
ln -s application-x-theme.svg gnome-mime-application-x-theme.svg
ln -s image-x-generic.svg image.svg
ln -s image-x-generic.svg image-generic.svg
ln -s image-jpeg.svg image-jpeg2000.svg
ln -s image-x-eps.svg image-svg+xml.svg
ln -s image-x-eps.svg image-svg+xml-compressed.svg
ln -s application-x-dgn.svg image-vnd.dwg.svg
ln -s message.svg application-mimearchive.svg
ln -s image-ico.svg image-vnd.microsoft.icon.svg 
ln -s image-x-generic.svg image-x-adobe-dng.svg
ln -s image-x-generic.svg image-x-krita.svg
ln -s image-x-generic.svg image-x-portable.bitmap.svg
ln -s image-x-eps.svg image-x-svg+xml.svg
ln -s image-x-generic.svg image-x-tga.svg
ln -s image-x-generic.svg image-x-win-bitmap.svg
ln -s image-x-generic.svg media-image.svg
ln -s image-x-generic.svg raw.svg
ln -s image-bmp.svg image-x-win-bmp.svg
ln -s x-office-drawing.svg image-x-xfig.svg
ln -s image-jpeg.svg jpeg.svg
ln -s image-jpeg.svg jpg.svg
ln -s x-office-drawing.svg libreoffice-drawing.svg
ln -s x-office-drawing.svg libreoffice-oasis-drawing.svg
ln -s x-office-drawing.svg libreoffice-oasis-drawing-template.svg
ln -s video-x-generic.svg media-video.svg
ln -s x-office-drawing.svg office-illustration.svg
ln -s x-office-drawing.svg openoffice3-drawing.svg
ln -s audio-x-generic.svg media-audio.svg
ln -s x-office-drawing.svg stock_new-drawing.svg_
ln -s image-x-eps.svg svg.svg
ln -s x-office-spreadsheet.svg text-csv.svg
ln -s text-rdf.svg text-rdf+xml.svg
ln -s text-richtext.svg text-rtf.svg
ln -s text-plain.svg text-sqml.svg
ln -s x-office-contact.svg text-x-authors.svg
ln -s text-plain.svg text-x-changlog.svg
ln -s text-plain.svg text-x-generic.svg
ln -s text-plain.svg text-x-log.svg
ln -s text-plain.svg text-x-nfo.svg
ln -s text-plain.svg text-x-plain.svg
ln -s vcalendar.svg text-calendar.svg
ln -s vcalendar.svg text-vcalendar.svg
ln -s text-x-readme.svg text-x-texinfo.svg
ln -s application-x-bittorrent.svg torrent.svg
ln -s video-x-generic.svg uri-mms.svg
ln -s video-x-generic.svg uri-mmst.svg
ln -s video-x-generic.svg uri-mmsu.svg
ln -s video-x-generic.svg uri-pnm.svg
ln -s video-x-generic.svg uri-rtspt.svg
ln -s video-x-generic.svg uri-rtspu.svg
ln -s video-x-generic.svg video.svg
ln -s video-x-generic.svg video-mlt-playlist.svg
ln -s video-x-generic.svg video-vivo.svg
ln -s video-x-mp4.svg video-mp4.svg
ln -s video-x-rmvb.svg video-vnd.rn-realvideo.svg
ln -s video-x-generic.svg video-wavelet.svg
ln -s video-x-generic.svg video-webm.svg
ln -s video-x-generic.svg video-x-anim.svg
ln -s video-x-generic.svg video-x-flic.svg
ln -s video-x-generic.svg video-x-google-vlc-plugin.svg
ln -s video-x-generic.svg video-x-javafx.svg
ln -s video-x-mkv.svg video-x-matroska.svg
ln -s video-x-generic.svg video-x-mng.svg
ln -s video-x-generic.svg video-x-ms-asf.svg
ln -s video-x-generic.svg video-x-ms-asf-plugin.svg
ln -s video-x-generic.svg video-x-ms-wmp.svg
ln -s video-x-generic.svg video-x-ms-wmv.svg
ln -s video-x-generic.svg video-x-nsv.svg
ln -s video-x-generic.svg video-x-ogm+ogg.svg
ln -s video-x-generic.svg video-x-sgi-movie.svg
ln -s video-x-generic.svg video-x-theora+ogg.svg
ln -s video-x-generic.svg video-x-wmv.svg
ln -s text-x-bak.svg application-x-trash.svg
ln -s application-msword.svg application-wps-office.doc.svg
ln -s application-vnd.ms-excel.svg application-wps-office.xlsx.svg
ln -s application-vnd.ms-excel.svg application-wps-office.xls.svg
ln -s application-vnd.ms-powerpoint.svg application-wps-office.ppt.svg
ln -s image-x-psd.svg image-vnd.adobe.photoshop.svg
ln -s video-x-mov.svg video-quicktime.svg
ln -s deb.svg application-vnd.debian.binary-package.svg
ln -s text-x-po.svg text-x-gettext-translation.svg
ln -s text-x-markdown.svg text-markdown.svg
ln -s text-x-script.svg application-x-shellscript.svg






